[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#aa70b802be8851668053d4f09734e4089fe41932
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0m
extra_scripts = pre:scripts/build_rust.py
monitor_speed = 115200
build_flags =
    -Os
    -ffunction-sections
    -fdata-sections
